### ISSUE TITLE
Update to fluentd-ui 0.4.3

### ISSUE THREAD

**Issue by jefe-spain** [vladnik/fluentd-ui#2]
hi @vladnik !, I'm trying to create an image from your dockerfile but it install the latest version of fluentd v0.14 with fluentd-ui v0.4.2 and It throw an error `worker 0 finished unexpectedly with status 0`, I think the latest version of fluentd-ui is 0.4.3 but I tried too and It's the same problem.

Any ideas please?

**Comment by zedtux** [comment]
The version 0.4.4 is now available.
